services:
  backend:
    build:
      context: ./backend-laravel
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
    depends_on:
      - db
      - db_test
    volumes:
      - ./backend-laravel:/var/www/html  # <- bind mount local code
      
  frontend:
    build:
      context: ./frontend_reactjs
    container_name: react_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:80/api/
    depends_on:
      - backend
    volumes:
      - ./frontend_reactjs:/app  # <- bind mount local code

  db:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root # Change this to a strong password
      MYSQL_DATABASE: crud_employees_laravel # Change this to your desired database name
      MYSQL_USER: laravel # Change this to your desired database user
      MYSQL_PASSWORD: 12345 # Change this to a strong password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  db_test:
    image: mysql:8
    container_name: mysql_test_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testing_db_employees
      MYSQL_USER: laravel_test
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"   # Avoid conflict with main DB
    volumes:
      - db_test_data:/var/lib/mysql

volumes:
  db_data:
  db_test_data: