services:
  backend:
    build:
      context: ./backend-laravel
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      APP_ENV: local
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
      - db_test
#    volumes:
#      - ./backend-laravel:/var/www/html  # <- bind mount local code
      
  frontend:
    build:
      context: ./frontend_reactjs
    container_name: react_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:80/api/
    depends_on:
      - backend
#    volumes:
#      - ./frontend_reactjs:/app  # <- bind mount local code

  db:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  db_test:
    image: mysql:8
    container_name: mysql_test_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_TEST_DATABASE}
      MYSQL_USER: ${MYSQL_TEST_USER}
      MYSQL_PASSWORD: ${MYSQL_TEST_PASSWORD}
    ports:
      - "3307:3306"   # Avoid conflict with main DB
    volumes:
      - db_test_data:/var/lib/mysql

volumes:
  db_data:
  db_test_data: