name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build

      - name: Start stack
        run: docker compose up -d

      - name: Clear Laravel config cache
        run: docker compose exec -T backend php artisan config:clear

      - name: See the env file
        run: docker compose exec backend php artisan tinker --execute="dump(app()->environment());dump(config('database.connections.mysql.host'));"

      - name: Run migrations
        run: docker compose exec -T backend php artisan migrate --env=testing

      - name: Run Laravel tests
        run: docker compose exec -T backend php artisan test

      - name: Run React tests
        run: docker compose exec -T frontend npm test -- --watch=false

      - name: Shutdown
        if: always()
        run: docker compose down -v