name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build

      - name: Start stack
        run: docker compose up -d

      - name: Clear Laravel config cache
        run: docker compose exec -T backend php artisan config:clear

      - name: See the env file with APP_ENV
        run: docker compose exec backend env APP_ENV=testing php artisan tinker --execute="dump(app()->environment());dump(config('database.connections.mysql.host'));"
      
      - name: Wait for test database
        run: |
          echo "Waiting for MySQL test DB..."
          until docker compose exec -T db_test mysqladmin ping -h localhost --silent; do
            sleep 2
          done
          
      - name: Test backend â†’ db_test network
        run: |
          echo "Ping test db_test from backend:"
          docker compose exec -T backend ping -c 3 db_test

          echo "Try MySQL connection from backend:"
          docker compose exec -T backend mysql -h db_test -P 3306 -u laravel_test -psecret -e "SELECT 1;" testing_db_employees

      #- name: Run migrations
      #  run: docker compose exec -T backend env APP_ENV=testing php artisan migrate

      - name: Run Laravel tests
        run: docker compose exec -T backend env APP_ENV=testing php artisan test

      - name: Run React tests
        run: docker compose exec -T frontend npm test -- --watch=false

      - name: Shutdown
        if: always()
        run: docker compose down -v